/**
 * /routes/index.js
 * @fileOverview Routing rules for Weblockly server
 * Base have been automatically generated by express-generator
 * Few modificatons have been made.
 * */

// Modules import (Generated by express-generator)
var express = require('express');
var path = require('path');
var router = express.Router();

// Renders frontend demo page (Written by our team)
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Weblockly' });
});

// Renders backend demo page (Written by our team)
router.get('/server', function(req, res) {
  res.render('server', {title: 'Weblockly Serverside Demo'});
});

module.exports = router;
